### ISSUE TITLE
Unable to integrate config into pipeline actions

### ISSUE THREAD

**Issue by twanbeeren** [Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines#20]
Regarding this issue 

https://github.com/backstage/backstage/issues/17923

**Comment by hevans-dglcom** [comment]
Hi,

It seems like the issue may have been a package version mismatch between our plugin and the core backstage version. (integration package).

You can fix this now by bumping backstage to the latest version, and bump our plugins to the following versions:

@parfuemerie-douglas/scaffolder-backend-module-azure-pipelines - 0.4.5-next.0
@parfuemerie-douglas/scaffolder-backend-module-azure-repositories - 0.2.4-next.2

Thanks,
Haydn
