### ISSUE TITLE
Can't send parameters to the pipeline using "values"

### ISSUE THREAD

**Issue by GreenDaniel** [Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines#21]
I manage to trigger the pipeline using Postman for example with the required parameters in the Body.
But when using the action: azure:pipeline:run the parameters I put under the "values" property are not taken into account.

Running a pipeline without parameters works fine.

steps:
    - id: runAzurePipeline
      name: Run Azure Pipeline
      action: azure:pipeline:run
      input:
        organization: myorg
        pipelineId: '1'
        project: myproject
        values:
          templateParameters:
            Param1: somestring
            Param2: 3

I also tried without templateParametes or with putting the object directly in JSON format.

Any ideas?

**Comment by hevans-dglcom** [comment]
Hi @GreenDaniel can you explain exactly what you want to acheive?

Do you want request parameters, or additional fields to be submitted with the body?
