### ISSUE TITLE
Unsupported api version in Azure DevOps Server while running pipeline

### ISSUE THREAD

**Issue by antoniobergas** [Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines#24]
https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines/blob/c19e28474abaf123fd8add06695db7d95b43470d/src/actions/run/runAzurePipeline.ts#L174

Hi! We are using Azure DevOps Server 2020 and the version api 7 fron the run pipeline action is not supported.

Could we have a new parameter to expose the version instead of having the version hardcoded? So we can fill it with the current one that its supported for our azdops ?

Something like:

``` typescript
properties: {
  apiVersion: {
    type: "string",
    title: "API Version",
    description: "The api version to use, default version 7",
  },
```
          
``` typescript
https://${host}/${organization}/${project}/_apis/pipelines/${pipelineId}/runs?api-version=${apiVersion}
```
@hevans-dglcom could this be possible? Just pending from this last step to make a cool golden path for a template 🚀

I'm willing to submit PR if preferred 😁

**Comment by hevans-dglcom** [comment]
Hi - I have no problems with you submitting a PR, just follow the same pattern as what we did for the host (falling back to a default if not specified).

I'm not sure if the request body changes between versions 5, 6 and 7 - if they do can you add that to the README (with an example) on what api versions are supported.

Thanks!

**Comment by hevans-dglcom** [comment]
thanks! I have pushed v1.0.0-next.5 with your changes :) let me know how you go with it

**Comment by antoniobergas** [comment]
Looks like its working fine 😁 thanks @hevans-dglcom
