### ISSUE TITLE
Cannot find name 'createBuiltInActions'

### ISSUE THREAD

**Issue by nalexeyev** [Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines#27]
Hi.
Please help me to get your plugin working. I do the similar things I did for another plugins such as plugin-azure-devops etc.
(I mean yarn add --cwd packages/backend @backstage/     and then editing some code in .ts files   and  then building Docker image).
But here I get
**error TS2304: Cannot find name 'createBuiltInActions'**

Steps to reproduce:
1. I created app according to the manual
https://backstage.io/docs/getting-started/create-an-app
2. Then I set up a multistage Docker build
https://backstage.io/docs/deployment/docker/#multi-stage-build 
3. And then I deploy the solution to k8s cluster using helm-chart
https://github.com/backstage/charts

Now on the step 2 I get docker build error like the following:
![image](https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines/assets/13438717/881f92f7-135a-421d-91bd-c47011de570f)

**Comment by antoniobergas** [comment]
Hi @nalexeyev, the error looks related to the createBuiltinActions which belongs to _@backstage/plugin-scaffolder-backend_ and not to the _@parfuemerie-douglas/scaffolder-backend-module-azure-pipelines_

Can you provide more info? For example how you scaffolder.ts file looks like in your backend folder?

In addition could you also run `yarn backstage-cli info` to provide more info about your current backstage instance?

Thanks

**Comment by epachols** [comment]
Hi! 

It looks to be a typo in the documentation, see


CreateBuilt **_i_** nActions

vs 

CreateBuilt **_I_** nActions

**Comment by antoniobergas** [comment]
You are right @epachols , didn't saw that one, will open a PR for it, Thanks! 😂

@nalexeyev try lower case the i in that function and tell us if that fix your issue!

**Comment by nalexeyev** [comment]
@antoniobergas It works, thank you
