### ISSUE TITLE
Template action with ID 'azure:pipeline:create' is not registered.

### ISSUE THREAD

**Issue by Akshay-Durgade** [Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines#43]
I have followed and installed Azure Pipeline Actions  using scaffolder-backend-module-azure-pipelines GitHub Repo. Even after following the steps, the desired actions are not being installed in my Backstage.

I followed the standalone server documentation to install Backstage. : https://backstage.io/docs/getting-started/

Followed by I installed the following actions : https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines

When I try to use the template it gives the following error `Template action with ID 'azure:pipeline:create' is not registered.`
Can someone help out me, why this actions are not visible in Backstage? 

Additionally if tweak and modify template to fetch the pipeline from GitHub, will the template work and create a pipeline?

**Comment by salfedev** [comment]
This work-around fixed it for me: https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines/issues/42
